export default {
  CHIP_LABEL: 'CHIP_LABEL',
  POSTER_IMAGE: 'POSTER_IMAGE',
  MOVIE_YEAR: 'MOVIE_YEAR',
  MOVIE_GENRES: 'MOVIE_GENRES',
  MOVIE_RATING_STAR: 'MOVIE_RATING_STAR',
  POPULAR_MOVIE_CARD: 'POPULAR_MOVIE_CARD',
  UPCOMING_MOVIE_CARD: 'UPCOMING_MOVIE_CARD',
};
