name: iOS - Detox

on: [push]
jobs:
  build:
    runs-on: macos-12
    env:
      NITRO_API_KEY: ${{ secrets.NITRO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Detox dependencies
        shell: bash
        run: |
          yarn global add detox-cli react-native-cli
          brew tap wix/brew
          brew install applesimutils
      - uses: nitro-build/github-action-nitro-ios@v1
        with:
          detox-configuration: ios.release
      - name: Run tests with Detox
        run: |
          detox test --configuration  ios.release --cleanup --headless
      - name: 🥳 Store screenshots and report as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: e2e-s
          path: ${{ github.workspace }}/artifacts